## quickstart 

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


Load and prepare the MNIST dataset. Convert the sample data from integers to floating-point numbers:

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
#For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.21507952, -0.44154176,  0.21920708,  0.41333815, -0.37588856,
        -0.3878473 ,  0.04879391,  0.3026399 , -0.1267052 , -0.11356628]],
      dtype=float32)

In [6]:
#The tf.nn.softmax function converts these logits to probabilities for each class:
tf.nn.softmax(predictions).numpy()

array([[0.08272638, 0.06596185, 0.12771806, 0.15508236, 0.07043777,
        0.06960043, 0.10770673, 0.1388311 , 0.09037005, 0.09156525]],
      dtype=float32)

In [7]:
#Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
# compile model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
# fit model 
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 2ms/step - loss: 0.3011 - accuracy: 0.9110
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1453 - accuracy: 0.9562
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1085 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0867 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0726 - accuracy: 0.9774


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0776 - accuracy: 0.9760 - 612ms/epoch - 2ms/step


[0.07763870805501938, 0.9760000109672546]

In [11]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.8489890e-07, 2.5707043e-09, 8.3837722e-06, 1.4085891e-03,
        4.6102540e-12, 1.1549603e-06, 4.0326591e-14, 9.9854881e-01,
        1.4838598e-06, 3.1273736e-05],
       [1.6611030e-07, 5.9051585e-04, 9.9939072e-01, 9.0528356e-06,
        6.6171993e-15, 8.7433227e-07, 2.0081949e-07, 2.4265738e-13,
        8.4266303e-06, 3.5994853e-12],
       [1.7577703e-07, 9.9907243e-01, 1.6606541e-04, 9.4954639e-06,
        1.4023326e-05, 3.4645077e-06, 1.3363221e-05, 3.7570461e-04,
        3.4507480e-04, 1.3908131e-07],
       [9.9972039e-01, 3.1747555e-07, 2.4189265e-05, 4.1753644e-08,
        4.0911101e-07, 1.3843427e-06, 2.4912111e-04, 2.8003401e-06,
        4.2735650e-08, 1.3975241e-06],
       [2.4973991e-05, 3.9285331e-09, 2.8199764e-04, 8.9965243e-07,
        9.7616982e-01, 1.2789390e-07, 3.3760350e-06, 1.0866525e-03,
        4.5961413e-05, 2.2386160e-02]], dtype=float32)>